[development]
address = "localhost"
port = 8000
workers = 2
keep_alive = 5
read_timeout = 5
write_timeout = 5
log = "normal"
secret_key = "hK+fGMo/DzW1k5EwcrGCxORN4rtudvzHodw5vl8DunI="
limits = { forms = 131072, json = 5242880 }

[staging]
address = "0.0.0.0"
port = 8000
workers = 2
keep_alive = 5
read_timeout = 5
write_timeout = 5
log = "normal"
secret_key = "hK+fGMo/DzW1k5EwcrGCxORN4rtudvzHodw5vl8DunI="
limits = { forms = 131072, json = 5242880 }

[production]
address = "0.0.0.0"
port = 8000
workers = 8
keep_alive = 5
read_timeout = 5
write_timeout = 5
log = "critical"
secret_key = "hK+fGMo/DzW1k5EwcrGCxORN4rtudvzHodw5vl8DunI="
limits = { forms = 131072, json = 5242880 }